### ISSUE TITLE
Hash passwords more securely using salted password hashing (pbkdf_hmac along with the SHA256)

### ISSUE THREAD

**Issue by NVombat** [SRM-IST-KTR/githubsrm#150]
# Expected Behavior

Passwords are more secure when hashed with salt and tend to be much harder to crack. Salted Password Hashing with SHA256 & pbkdf_hmac2 is very secure and widely used.

# Current Behavior

Currently the admin site hashes passwords only using the SHA256. Adding another level of complexity with salt and the pbkdf_hmac2 will improve security

```
HASHING: 
def hash_pwd(pwd : str):
    salt = hashlib.sha256(os.urandom(60)).hexdigest().encode('ascii')
    pwd_hash = hashlib.pbkdf2_hmac('sha512', pwd.encode('utf-8'), salt, 100000)
    pwd_hash = binascii.hexlify(pwd_hash)
    final_hashed_pwd = (salt + pwd_hash).decode('ascii')
    return final_hashed_pwd
```

**Comment by Aradhya-Tripathi** [comment]
Hey, @NVombat thanks for your issue.
Unsalted hashed passwords are a common practice as well however if you do feel this is a meaningful/necessary issue that needs to be fixed we would love to see a pr from your side 🥳 🚀🎉
