### ISSUE TITLE
Pagination changes 

### ISSUE THREAD

**Issue by sakshi-choudhary** [SRM-IST-KTR/githubsrm#194]
- Fast forward to the last page button
- Fast forward to first-page button

**Comment by jagnani73** [comment]
Will be implemented in maintainers portal as well

**Comment by Codered9** [comment]
I am interested in this issue and I have the code almost ready. But I only need to test it somehow.

**Comment by sakshi-choudhary** [comment]
> I am interested in this issue and I have the code almost ready. But I only need to test it somehow.

Sure! Go ahead.
