### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by saxenabhishek** [SRM-IST-KTR/githubsrm#39]
# Expected Behavior

NOT add beta Maintainer to project doc when not approved

https://github.com/SRM-IST-KTR/githubsrm/blob/182f363f2ef8be1dae5353cba0deda7b734c85a0/server/githubsrm/apis/models.py#L124-L126

# Current Behavior

It needs approval

## Context

Check-out flow

**Comment by Aradhya-Tripathi** [comment]
Resolved
